import { StyleSheet, Text, View } from 'react-native';
import { Colors } from 'react-native/Libraries/NewAppScreen';

const Styles_3a = StyleSheet.create({ 
    view_header:{
        flex:1,
        width:'100%',
        left:10,
    },
    image_header:{
        width:104,
        height:147,
        top:80,
        left:-22,
    },
    text_header1:{
        fontSize:12,
        lineHeight:14.06,
        fontWeight:'bold',
        left:101,
        top:-70,
    },
    text_header2:{
        fontSize:12,
        lineHeight:14.06,
        fontWeight:'bold',
        left:101,
        top:-50,
    },
    text_gia1:{
        color:'red',
        fontWeight:'bold',
        fontSize:18,
        lineHeight:21.09,
        left:101,
        top:-30,
    },
    text_gia2:{
        color:'gray',
        fontWeight:'bold',
        fontSize:12,
        lineHeight:14.06,
        left:103,
        top:-20,
        textDecorationLine:'line-through',
    },
    container_view:{
        flexDirection:'row',
        left:103,
        top:-10,
    },
    text_tru:{
        backgroundColor:'gray',
        width:14.22,
        height:16,
        alignItems:'center',
        justifyContent:'center',
        fontSize:20,
        paddingRight:0
    },
    text_cong:{
        backgroundColor:'gray',
        width:14.22,
        height:16,
        alignItems:'center',
        justifyContent:'center',
        fontSize:20,
        paddingRight:0
    },
    text_soSP:{
        fontSize:15,
        lineHeight:17.58,
        paddingLeft:10,
        paddingRight:10,
    },
    text_muaSau:{
        color:'blue',
        fontSize:15,
        lineHeight:17.58,
        right:-70,
        fontWeight:'bold'
    },
    container_row:{
        top:25,
        flexDirection:'row',
        left:-22
    },
    text_maGiam1:{
        fontSize:12,
        lineHeight:14.06,
        fontWeight:'bold',
        paddingRight:20,
    },
    text_maGiam2:{
        fontSize:12,
        lineHeight:14.06,
        fontWeight:'bold',
        color:'blue'
    },
    container_border_1:{
        width:208,
        height:45,
        borderWidth:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
    },
    container_row1:{
        top:60,
        flexDirection:'row',
        left:-22,
        alignItems:'center',
        justifyContent:'center',
    },
    view_yellow:{
        width:32,
        height:16,
        backgroundColor:'yellow',
        left:-30
    },
    text_maGiam3:{
        fontSize:18,
        fontWeight:'bold',
        lineHeight:21.09,
        left:-20
    },
    btn_ApDung:{
        width:99,
        height:45,
        backgroundColor:'#0A5EB7',
        right:-30,
        justifyContent:'center',
        alignItems:'center'
    },
    text_ApDung:{
        fontSize:20,
        lineHeight:23.44,
        fontWeight:'bold',
        color:'#FFFFFF',
    },
    container_row2:{
        flex:2,
        flexDirection:'row',
        width:'100%',
        top:310,
        height:51
    },
    text_maGiam4:{
        fontSize:12,
        fontWeight:'bold',
        lineHeight:14.06,
    },
    text_maGiam5:{
        fontSize:12,
        fontWeight:'bold',
        lineHeight:14.06,
        color:'#134FEC'
    },
    container_row3:{
        flex:3,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        top:110,
        left:-90
    },
    text_tamTinh:{
        fontSize:18,
        lineHeight:21.09,
        fontWeight:'bold'
    },
    text_tongTien1:{
        fontSize:18,
        lineHeight:21.09,
        fontWeight:'bold',
        color:'#EE0D0D',
        right:-180
    },
    container_col4:{
        flex:4,
        top:200,
        left:-10,
        right:10
    },  
    container_row4:{
        flexDirection:'row'
    } ,
    text_thanhTien:{
        fontSize:18,
        fontWeight:'bold',
        color:'#808080',

    },
    text_tienHanhDatHang:{
        fontSize:20,
        fontWeight:'700',
        color:'#FFFFFF'
    },
    btn_tienHanhDatHang:{
        width:331,
        height:45,
        backgroundColor:'#E53935',
        top:10,
        justifyContent:'center',
        alignItems:'center'
    },
    text_tongTien2:{
        fontSize:20,
        lineHeight:21.09,
        fontWeight:'bold',
        color:'#EE0D0D',
        right:-150
    },
});
export default Styles_3a;